[workspace]
members = ["macros"]

[package]
name = "macro_magic"
version = "0.1.0"
edition = "2021"
authors = ["sam0x17"]
license = "MIT"
keywords = ["macro", "macros", "proc-macro", "proc-macros", "magic"]
categories = ["development-tools", "development-tools::procedural-macro-helpers", "rust-patterns"]
website = "https://sam0x17.dev"
repository = "https://github.com/sam0x17/macro_magic"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0", features = ["full"] }
macros = { version = "*", path = "./macros" }

[dev-dependencies]
example_crate = { version = "*", path = "./tests/example_crate" }
example_proc_macro = { version = "*", path = "./tests/example_proc_macro" }
example_crate2 = { version = "*", path = "./tests/example_crate2" }

[features]
default = []
verbose = ["macros/verbose"]
indirect = [
    "macros/indirect",
    "example_proc_macro/indirect",
    "example_crate/indirect",
    "example_crate2/indirect"
]
