[workspace]
members = ["macros"]

[package]
name = "macro_magic"
version = "0.1.0"
edition = "2021"
authors = ["sam0x17"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = { version = "*", path = "./macros" }
syn = { version = "1.0", features = ["full"] }
