[workspace]
members = ["level1_macros", "level2_macros"]

[package]
name = "macro_magic"
version = "0.1.0"
edition = "2021"
authors = ["sam0x17"]
license = "MIT"
keywords = ["macro", "macros", "proc-macro", "proc-macros", "magic"]
categories = ["development-tools", "development-tools::procedural-macro-helpers", "rust-patterns"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0", features = ["full"] }
level1_macros = { version = "*", path = "./level1_macros" }
level2_macros = { version = "*", path = "./level2_macros" }

[dev-dependencies]
example_crate = { version = "*", path = "./tests/example_crate" }
example_proc_macro = { version = "*", path = "./tests/example_proc_macro" }
