[package]
name = "macro_magic_core"
version = "0.2.2"
edition = "2021"
description = "Core implementation behind macro_magic"
repository = "https://github.com/sam0x17/macro_magic"
homepage = "https://sam0x17.dev"
license = "MIT"

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
prettyplease = "0.1"
derive-syn-parse = "0.1.5"
proc-macro2 = "1.0"
convert_case = "0.6.0"
macro_magic_core_macros = { version = "0.2.2", path = "../core_macros" }
