[package]
name = "macro_magic_core"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
atomicwrites = { version = "0.4.0", optional = true }

[features]
default = []
verbose = []
indirect = ["indirect-read", "indirect-write"]
indirect-read = []
indirect-write = ["dep:atomicwrites"]
