[package]
name = "macros"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_format = "0.2"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
